<?php
/**
 * Created by PhpStorm.
 * User: zhu
 * Date: 11/12/18
 * Time: 4:17 PM
 */

namespace Tests;


use App\Exceptions\CustomValidationException;
use App\Models\AuthCustomerToken;

class WapApiTest extends TestCase
{
    protected $prefix = 'wap/';
    // protected $prefix = '';

    protected $token;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->token = AuthCustomerToken::where([
            'status'        => 1,
            
            'customer_id' => 1298,
        ])->latest()->first()->token;
    }

    public function authenticated_get($data = [])
    {
        return $resource = $this
            ->withHeader('token', $this->token)
            ->json("GET", $this->getUri(), $data);
    }

    public function authenticated_post($data = [])
    {
        return $resource = $this
            ->withHeader('token', $this->token)
            ->json("POST", $this->getUri(), $data);
    }


    public function authenticated_get_with_company($data = [])
    {
        return $resource = $this
            ->withHeader('token', $this->token)
            ->json("GET", $this->getUri(),
                array_merge($data, ['company_id' => 1])
            );
    }

    public function authenticated_post_with_company($data = [])
    {
        return $resource = $this
            ->withHeader('token', '123465')
            ->json("POST", $this->getUri(),
                array_merge($data, ['company_id' => 1])
            );
    }

    public function getUri()
    {
        if (empty($this->uri)) {
            throw new CustomValidationException('没有设置 uri');
        }

        return $this->prefix . $this->uri;
    }

}